micronaut:
  application:
    name: beanstalkCore


datasources:
  default:
    url: jdbc:cloudspanner:/projects/test/instances/my-instance-id/databases/database-id;autoConfigEmulator=true
    driverClassName: com.google.cloud.spanner.jdbc.JdbcDriver
    schema-generate: CREATE

jpa:
  default:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: com.google.cloud.spanner.hibernate.SpannerDialect
        show_sql: true
